const Hapi = require('hapi');
const chalk = require('chalk');

// feed generator
const feed = require('../feed/feed');

// Create a server with a host and port
const server = Hapi.server({
  host: 'localhost',
  port: process.env.FEED_SERVER_PORT || '8000',
});

// Add the route
server.route({
  method: 'GET',
  path: '/',
  handler: function(request, h) {
    return 'OK';
  },
});

// probe status url
server.route({
  method: 'GET',
  path: '/probe_status',
  handler: function(request, h) {
    return 'OK';
  },
});

// ROUTE for FEEDS generated by the python gql service
server.route({
  method: 'GET',
  path: '/feed_gql',
  handler: async (request, h) => {
    try {
      return await feed.getGqlFeed();
    } catch (e) {
      console.error(e);
      return e;
    }
  },
});

// ROUTE for FEEDS generated by node
// - known limitations: the mp3 files are generated with a link to Google's
//   TTS service. But this causes some troubles when working with audio/video
//   skills on Alexa. The files are available after the first request only.
server.route({
  method: 'GET',
  path: '/feed',
  handler: async (request, h) => {
    try {
      return (await feed.getFeed()).map(feed => feed.toBriefing());
    } catch (e) {
      console.error(e);
      return e;
    }
  },
});

server.route({
  method: 'GET',
  path: '/feed_with_audio',
  handler: async (request, h) => {
    try {
      const feedItems = (await feed.getFeed()) || [];
      const toVideoBriefingPromise = feedItems.map(
        item => item.toAudioBriefing(), // attention: this is an async method
      );
      return await Promise.all(toVideoBriefingPromise);
    } catch (e) {
      console.error(e);
      return e;
    }
  },
});

server.route({
  method: 'GET',
  path: '/feed_with_video',
  handler: async (request, h) => {
    try {
      const feedItems = (await feed.getFeed()) || [];
      const toVideoBriefingPromise = feedItems.map(
        item => item.toVideoBriefing(), // attention: this is an async method
      );
      return await Promise.all(toVideoBriefingPromise);
    } catch (e) {
      console.error(e);
      return e;
    }
  },
});

// Start the server
async function start() {
  try {
    await server.start();
  } catch (err) {
    console.log(err);
    process.exit(1);
  }
  console.log(chalk.green(`>> LOCAL: feed running at: ${server.info.uri}`));
}

module.exports = {
  start: start,
};
